import 'dart:async';

import 'package:flutter/material.dart';

import 'mobile_excel_export.dart';

final class MobileExcelExportScreen extends StatelessWidget {
  const MobileExcelExportScreen({required this.controller, super.key});

  final MobileExcelExportController controller;

  @override
  Widget build(BuildContext context) {
    return AnimatedBuilder(
      animation: controller,
      builder: (context, child) {
        final filters = controller.filtersProvider();
        final busy = controller.state == ExcelExportState.loading;

        return ListView(
          padding: const EdgeInsets.all(16),
          children: [
            Text(
              'Excel export',
              style: Theme.of(context).textTheme.headlineSmall,
            ),
            const SizedBox(height: 8),
            const Text(
              'The workbook is generated by SafeContracts on the server using '
              'your current authorized dashboard filters.',
            ),
            const SizedBox(height: 16),
            Card(
              child: Padding(
                padding: const EdgeInsets.all(16),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Text(
                      'Current filters',
                      style: Theme.of(context).textTheme.titleMedium,
                    ),
                    const SizedBox(height: 12),
                    _FilterValue(
                      label: 'Customer',
                      value: filters.customerId?.toString() ?? 'All customers',
                    ),
                    _FilterValue(
                      label: 'Contract',
                      value: filters.contractId?.toString() ?? 'All contracts',
                    ),
                    _FilterValue(
                      label: 'Status',
                      value: filters.status ?? 'All statuses',
                    ),
                    _FilterValue(
                      label: 'Due from',
                      value: filters.dueFrom ?? 'Any date',
                    ),
                    _FilterValue(
                      label: 'Due to',
                      value: filters.dueTo ?? 'Any date',
                    ),
                  ],
                ),
              ),
            ),
            const SizedBox(height: 12),
            FilledButton.icon(
              onPressed: busy || !controller.canExport
                  ? null
                  : () => unawaited(controller.downloadCurrentFilters()),
              icon: const Icon(Icons.file_download_outlined),
              label: Text(busy ? 'Generating Excel…' : 'Download Excel'),
            ),
            if (busy) ...[
              const SizedBox(height: 12),
              const LinearProgressIndicator(),
            ],
            if (!controller.canExport) ...[
              const SizedBox(height: 12),
              const _ExportMessage(
                icon: Icons.lock_outline,
                message: 'Excel export is not authorized for this session.',
              ),
            ],
            if (controller.state == ExcelExportState.error &&
                controller.errorMessage != null) ...[
              const SizedBox(height: 12),
              _ExportMessage(
                icon: Icons.error_outline,
                message: controller.errorMessage!,
                isError: true,
              ),
            ],
            if (controller.state == ExcelExportState.ready &&
                controller.lastExport != null) ...[
              const SizedBox(height: 12),
              _ExportSuccess(
                export: controller.lastExport!,
                savedPath: controller.savedPath,
                onClear: controller.clearResult,
              ),
            ],
          ],
        );
      },
    );
  }
}

final class _FilterValue extends StatelessWidget {
  const _FilterValue({required this.label, required this.value});

  final String label;
  final String value;

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.only(bottom: 6),
      child: Row(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            width: 96,
            child: Text(
              label,
              style: Theme.of(context).textTheme.labelMedium,
            ),
          ),
          Expanded(child: Text(value)),
        ],
      ),
    );
  }
}

final class _ExportSuccess extends StatelessWidget {
  const _ExportSuccess({
    required this.export,
    required this.savedPath,
    required this.onClear,
  });

  final MobileExcelExport export;
  final String? savedPath;
  final VoidCallback onClear;

  @override
  Widget build(BuildContext context) {
    final sizeKb = (export.bytes.length / 1024).toStringAsFixed(1);
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Row(
              children: [
                const Icon(Icons.check_circle_outline),
                const SizedBox(width: 8),
                Expanded(
                  child: Text(
                    'Excel export ready',
                    style: Theme.of(context).textTheme.titleMedium,
                  ),
                ),
              ],
            ),
            const SizedBox(height: 12),
            Text(export.filename),
            Text('$sizeKb KB'),
            if (savedPath != null) ...[
              const SizedBox(height: 8),
              Text(
                'Saved in app cache:',
                style: Theme.of(context).textTheme.labelMedium,
              ),
              SelectableText(savedPath!),
            ],
            if (export.rowCounts.isNotEmpty) ...[
              const SizedBox(height: 12),
              Text(
                'Rows exported',
                style: Theme.of(context).textTheme.labelLarge,
              ),
              const SizedBox(height: 4),
              ...export.rowCounts.entries.map(
                (entry) => Text('${entry.key}: ${entry.value}'),
              ),
            ],
            const SizedBox(height: 12),
            TextButton(onPressed: onClear, child: const Text('Clear result')),
          ],
        ),
      ),
    );
  }
}

final class _ExportMessage extends StatelessWidget {
  const _ExportMessage({
    required this.icon,
    required this.message,
    this.isError = false,
  });

  final IconData icon;
  final String message;
  final bool isError;

  @override
  Widget build(BuildContext context) {
    final color = isError ? Theme.of(context).colorScheme.error : null;
    return Card(
      child: Padding(
        padding: const EdgeInsets.all(16),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Icon(icon, color: color),
            const SizedBox(width: 8),
            Expanded(child: Text(message, style: TextStyle(color: color))),
          ],
        ),
      ),
    );
  }
}
