#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

find "$ROOT/wordpress-plugin/safecontracts" "$ROOT/tests/php" -name '*.php' -print0 \
  | xargs -0 -n1 php -l >/dev/null
php -l "$ROOT/scripts/collect_alkenzy_production_preflight.php" >/dev/null

php "$ROOT/tests/php/run.php"
php "$ROOT/tests/php/contracts_schema.php"
php "$ROOT/tests/php/contracts_workflow.php"
php "$ROOT/tests/php/contracts_financials.php"
php "$ROOT/tests/php/contracts_history.php"
php "$ROOT/tests/php/contracts_validation_017_021.php"
php "$ROOT/tests/php/contracts_validation_022_023.php"
php "$ROOT/tests/php/payments_core.php"
php "$ROOT/tests/php/payments_due_collections.php"
php "$ROOT/tests/php/payments_settlement.php"
php "$ROOT/tests/php/payments_validation_014_018.php"
php "$ROOT/tests/php/payments_validation_019_023.php"
php "$ROOT/tests/php/payments_validation_024.php"
php "$ROOT/tests/php/followup_audit_001_009.php"
php "$ROOT/tests/php/followup_audit_validation_010_015.php"
php "$ROOT/tests/php/notifications_rules_001_004.php"
php "$ROOT/tests/php/audit_wordpress_event_payloads.php"
php "$ROOT/tests/php/notifications_delivery_005_013.php"
php "$ROOT/tests/php/notifications_validation_014.php"
php "$ROOT/tests/php/notifications_validation_015_019.php"
php "$ROOT/tests/php/notifications_validation_020_024.php"
php "$ROOT/tests/php/notifications_validation_025_026.php"
php "$ROOT/tests/php/admin_ui_001_003.php"
php "$ROOT/tests/php/admin_ui_004_008.php"
php "$ROOT/tests/php/admin_ui_009_013.php"
php "$ROOT/tests/php/admin_ui_014_018.php"
php "$ROOT/tests/php/admin_ui_019_023.php"
php "$ROOT/tests/php/admin_ui_validation_024_028.php"
php "$ROOT/tests/php/admin_ui_validation_029_033.php"
php "$ROOT/tests/php/admin_ui_validation_034_038.php"
php "$ROOT/tests/php/p6_post_validation_hardening.php"
php "$ROOT/tests/php/admin_ui_validation_039_040.php"
php "$ROOT/tests/php/admin_safe_deletion_currency_400.php"
php "$ROOT/tests/php/translations_404.php"
php "$ROOT/tests/php/translation_completeness_586.php"
php "$ROOT/tests/php/arabic_runtime_surface_594.php"
php "$ROOT/tests/php/production_migration_guard_586.php"
php "$ROOT/tests/php/production_ux_contract_586.php"
php "$ROOT/tests/php/admin_navigation_groups_592.php"
php "$ROOT/tests/php/production_preflight_collector_590.php"
php "$ROOT/tests/php/brand_identity_silent_refresh_411.php"
php "$ROOT/tests/php/admin_apk_attachments_status_period_414.php"
php "$ROOT/tests/php/admin_notification_schedule_416.php"
php "$ROOT/tests/php/admin_notification_center_archive_presence_418.php"
php "$ROOT/tests/php/responsible_accountant_delivery_end_to_end.php"
php "$ROOT/tests/php/rest_api_001_010.php"
php "$ROOT/tests/php/rest_api_011_015.php"
php "$ROOT/tests/php/rest_api_016_017.php"
php "$ROOT/tests/php/import_foundation_001_008.php"
php "$ROOT/tests/php/import_validation_009_017.php"
php "$ROOT/tests/php/rest_api_validation_018.php"
php "$ROOT/tests/php/rest_api_validation_019_028.php"
php "$ROOT/tests/php/p10_security_financial_001_005.php"
php "$ROOT/tests/php/p10_ops_verification_006_010.php"
php "$ROOT/tests/php/p10_release_readiness_011_016.php"
php "$ROOT/tests/php/p10_validation_017_026.php"
php "$ROOT/tests/php/rest_mobile_notifications_020_025.php"
php "$ROOT/tests/php/rest_mobile_013_015.php"
php "$ROOT/tests/php/rest_mobile_mutations_016_019.php"
php "$ROOT/tests/php/mobile_crud_permissions_icon.php"
php "$ROOT/tests/php/p9_validation_038_044.php"
php "$ROOT/tests/php/mobile_auth_firebase_release.php"
php "$ROOT/tests/php/firebase_service_account_vault.php"
php "$ROOT/tests/php/fcm_device_registration_diagnostics.php"
php "$ROOT/tests/php/fcm_test_notification_fanout.php"
php "$ROOT/tests/php/fcm_invalid_token_recovery.php"
php "$ROOT/tests/php/p11_counterparty_supplier_apar.php"
php "$ROOT/tests/php/p11_finance_dashboard_002.php"
php "$ROOT/tests/php/p11_finance_reports_003.php"
php "$ROOT/tests/php/p11_finance_security_004.php"
