#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

find "$ROOT/wordpress-plugin/safecontracts" "$ROOT/tests/php" -name '*.php' -print0 \
  | xargs -0 -n1 php -l >/dev/null

php "$ROOT/tests/php/run.php"
php "$ROOT/tests/php/contracts_schema.php"
php "$ROOT/tests/php/contracts_workflow.php"
php "$ROOT/tests/php/contracts_financials.php"
php "$ROOT/tests/php/contracts_history.php"
php "$ROOT/tests/php/contracts_validation_017_021.php"
php "$ROOT/tests/php/contracts_validation_022_023.php"
php "$ROOT/tests/php/payments_core.php"
php "$ROOT/tests/php/payments_due_collections.php"
php "$ROOT/tests/php/payments_settlement.php"
php "$ROOT/tests/php/payments_validation_014_018.php"
php "$ROOT/tests/php/payments_validation_019_023.php"
php "$ROOT/tests/php/payments_validation_024.php"
php "$ROOT/tests/php/followup_audit_001_009.php"
php "$ROOT/tests/php/followup_audit_validation_010_015.php"
php "$ROOT/tests/php/notifications_rules_001_004.php"
php "$ROOT/tests/php/audit_wordpress_event_payloads.php"
php "$ROOT/tests/php/notifications_delivery_005_013.php"
php "$ROOT/tests/php/notifications_validation_014.php"
php "$ROOT/tests/php/notifications_validation_015_019.php"
php "$ROOT/tests/php/notifications_validation_020_024.php"
php "$ROOT/tests/php/notifications_validation_025_026.php"
php "$ROOT/tests/php/admin_ui_001_003.php"
php "$ROOT/tests/php/admin_ui_004_008.php"
php "$ROOT/tests/php/admin_ui_009_013.php"
php "$ROOT/tests/php/admin_ui_014_018.php"
php "$ROOT/tests/php/admin_ui_019_023.php"
php "$ROOT/tests/php/admin_ui_validation_024_028.php"
php "$ROOT/tests/php/admin_ui_validation_029_033.php"
php "$ROOT/tests/php/admin_ui_validation_034_038.php"
php "$ROOT/tests/php/p6_post_validation_hardening.php"
php "$ROOT/tests/php/admin_ui_validation_039_040.php"
php "$ROOT/tests/php/rest_api_001_010.php"
php "$ROOT/tests/php/rest_api_011_015.php"
php "$ROOT/tests/php/rest_api_016_017.php"
php "$ROOT/tests/php/import_foundation_001_008.php"
